name: pycbc-environment
channels:
  - default
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pycbc
  - nbgitpuller
  - ipykernel
  - gcc_linux-64
  - gxx_linux-64
  - gsl
  - lapack=3.6.1
  - numpy
  - scipy
  - Cython
  - jupyter
  - ipython
  - matplotlib
  - dynesty
  - pip:
    - git+https://github.com/mikekatz04/BBHx.git@4fff509
    - git+https://github.com/gwastro/BBHX-waveform-model.git
    - git+https://github.com/gwastro/pycbc.git